### ISSUE TITLE
Runtime Error: Experiencing issue fetching ISD temperature data

### ISSUE THREAD

**Issue by TechMaz** [openeemeter/eeweather#58]
**Describe the bug**
Calls to methods to pull ISD temperature data raise an exception:
`RuntimeError: Could not connect to ftp.ncdc.noaa.gov`

**To Reproduce**
1. call .load_isd_hourly_temp_data() on a station
Exception encountered:
```   def _get_noaa_ftp_connection(n_tries=5, timeout=60):  # pragma: no cover
        host = "ftp.ncdc.noaa.gov"
        for i in range(n_tries):
            # attempt anonymous connection
            try:
                ftp = ftplib.FTP(host, timeout=timeout)
                ftp.login()  # default u='anonymous' p='anonymous@'
                logger.info("Connected to {}.".format(host))
                return ftp
            except ftplib.all_errors as e:
                logger.warn(
                    "Failed attempt ({} of {}) to connect to {}:\n{}".format(
                        i + 1, n_tries, host, e
                    )
                )
    
>       raise RuntimeError("Could not connect to {}.".format(host))
E       RuntimeError: Could not connect to ftp.ncdc.noaa.gov.

../../envs/ohm/lib/python2.7/site-packages/eeweather/connections.py:50: RuntimeError
----------------------------------- Captured stderr call -----------------------------------
2019-11-25 16:01:29,508 WARNING: Failed attempt (1 of 5) to connect to ftp.ncdc.noaa.gov:
530-Unable to set anonymous privileges.
530 Login incorrect.
2019-11-25 16:01:30,036 WARNING: Failed attempt (2 of 5) to connect to ftp.ncdc.noaa.gov:
530-Unable to set anonymous privileges.
530 Login incorrect.
2019-11-25 16:01:30,600 WARNING: Failed attempt (3 of 5) to connect to ftp.ncdc.noaa.gov:
530-Unable to set anonymous privileges.
530 Login incorrect.
2019-11-25 16:01:31,107 WARNING: Failed attempt (4 of 5) to connect to ftp.ncdc.noaa.gov:
530-Unable to set anonymous privileges.
530 Login incorrect.
2019-11-25 16:01:31,511 WARNING: Failed attempt (5 of 5) to connect to ftp.ncdc.noaa.gov:
530-Unable to set anonymous privileges.
530 Login incorrect.```

**Expected behavior**
Normally returns data from NOAA or returns an expected error code

**Comment by ssuffian** [comment]
Thanks for the heads up! It appears that NOAA's FTP is down for this week. I found the following alert when going to https://www.ncdc.noaa.gov/isd/data-access

```Please note: Due to scheduled maintenance, many NCEI systems will be unavailable during the week of 11/25/2019 - 11/29/2019.```

**Comment by steevschmidt** [comment]
Internally we use [Mesonet](https://mesonet.agron.iastate.edu/) data to address short term delays in ISD data. We fetch Mesonet data for the most recent 14 days and then overwrite these earlier [temporary & low quality] values with ISD data when it becomes available.  Just fyi.

**Comment by philngo** [comment]
Since NOAA's data access is restored, I'm going to go ahead and close this issue. Any other suggestions or pull requests like @steevschmidt 's for how to handle this situation more gracefully would still be appreciated.

@TechMaz: If you have a minute, would you mind filling our our new first-time issue contributor survey? The info we get from this will help us to grow to meet the needs of our community of users. https://forms.gle/H5jptzS5rL3hDcNJA Thanks!
