### ISSUE TITLE
TMY3 Files are not been retrieved.

### ISSUE THREAD

**Issue by zf1990** [openeemeter/eeweather#63]
**Describe the bug**

Looks like the url to the TMY3 link is broken as listed under fetch_tmy3_hourly_temp.  File name is stations.py

url = (
        "http://rredc.nrel.gov/solar/old_data/nsrdb/"
        "1991-2005/data/tmy3/{}TYA.CSV".format(usaf_id)
    )

**To Reproduce**
1. Go to Scripts/Tutorial
2. Click on "Run all'
3. Scroll down to 'Cell 20 or 21.'

**Expected behavior**
Jupyter Notebook Error: Could not find http://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/data/tmy3/722880TYA.CSV.

**Screenshots**
![image](https://user-images.githubusercontent.com/54919155/87951309-078b3b80-ca6e-11ea-857f-fedef42f7b3e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]. 
Irrelevant

**Additional context**

**Comment by philngo** [comment]
Thank you for calling this to our attention. It does appear that the NREL is no longer hosting the files at that location. It does appear that the files are still available for bulk download, so I will see if I can find a place to host the files elsewhere and make a library update to point at that new location. An alternative solution for the longer term might be to update this use the new NREL API, if it is practical to do so. A further solution might be to derive the TMY data directly from the source ISD database, if that is practical. I'll aim for the first short term fix for now.

**Comment by UGuntupalli** [comment]
@philngo, 
        One other observation in looking through the available methods - is there any reason why there is a method only to retrieve TMY3 temperature ? TMY3 comprises of other useful weather datasets, if and when you look into this, it might be worthwhile to look into expanding beyond just temperature data. I am going to take a stab at NREL API to retrieve the TMY3 data. Feel free to tag me when you start looking at that. If I have anything, I will try and contribute

**Comment by ajaiswalopinionynamics** [comment]
@philngo,
Is there any update on TMY3 NREL API issue? Do we know by when a new release of this package is planned with this issue resolved?

**Comment by bhough199** [comment]
@philngo I'd also like to know if there is an update on when this issue might make it onto your roadmap?  I found the location where I can do a bulk download of these files (https://nsrdb.nrel.gov/data-sets/archives.html), but now need to decide if I should build a workaround separate from eeweather or if the TMY functionality might show back up soon.  Thanks for all your work on this package!

**Comment by philngo** [comment]
Sorry for the delay here, I've got a PR for this change. Currently uploading archived files to the new source. Thanks for the link! https://github.com/openeemeter/eeweather/pull/65

**Comment by philngo** [comment]
This should be ready, let me know if it works for you!

**Comment by ajaiswalopinionynamics** [comment]
@philngo 
Thanks for the update!
However, I am still getting the same error.
RuntimeError: Could not find http://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/data/tmy3/723440TYA.CSV.

**Comment by philngo** [comment]
@ajaiswalopinionynamics @zf1990 @bhough199 Oops - my bad! I totally forgot to release a new version. It's up on PyPI now at eeweather==0.3.24 with the fix.

**Comment by ajaiswalopinionynamics** [comment]
@philngo Thanks! This time it worked.
