### ISSUE TITLE
CA_Building_Standards_Climate_Zones.zip is not found

### ISSUE THREAD

**Issue by bhough199** [openeemeter/eeweather#67]
When rebuilding the database the file `scripts/create_ca_climate_zone_geojson.sh` tries to download http://ww2.energy.ca.gov/maps/renewable/CA_Building_Standards_Climate_Zones.zip but that climate zone file doesn't exist at that location anymore.  I found a copy of the file at https://community.esri.com/ccqpr47374/attachments/ccqpr47374/coordinate-reference-systemsforum-board/1814/1/CA_Building_Standards_Climate_Zones.zip but this is not a stable link.  I suggest hosting your own version of this (and other source files) in the same place you've started hosting the TMY3 data.

**To Reproduce**
1. Delete `eeweather/resources/metadata.db`
2. `docker-compose build`
3. `docker-compose run --rm --entrypoint "bash -c" eeweather bash
4. (from inside the shell) `eeweather rebuild-db`
5. That rebuild-db command will fail because it can't find this file.

**Expected behavior**
When you rebuild the database all of the source files are found and `rebuild-db` completes successfully.

**Comment by ssuffian** [comment]
This should be resolved now.
